"""Add ir_level column to sensor_readings

Revision ID: 18e1952699e5
Revises: 69ede00f27ea
Create Date: 2025-09-14 08:47:02.749061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e1952699e5'
down_revision = '69ede00f27ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ir_level', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_column('ir_level')

    # ### end Alembic commands ###
